HTMLElement.prototype.wrap=function(o){this.parentNode.insertBefore(o,this);this.parentNode.removeChild(this);o.appendChild(this)};Fluid.events={registerNavbarEvent:function(){var o=$("#navbar");var r=$("#navbar .dropdown-menu");if(o.offset().top>0){o.removeClass("navbar-dark");r.removeClass("navbar-dark")}Fluid.utils.listenScroll(function(){o[o.offset().top>50?"addClass":"removeClass"]("top-nav-collapse");r[o.offset().top>50?"addClass":"removeClass"]("dropdown-collapse");if(o.offset().top>0){o.removeClass("navbar-dark");r.removeClass("navbar-dark")}else{o.addClass("navbar-dark");r.removeClass("navbar-dark")}});$("#navbar-toggler-btn").on("click",function(){$(".animated-icon").toggleClass("open");$("#navbar").toggleClass("navbar-col-show")})},registerParallaxEvent:function(){var a=$('#banner[parallax="true"]');if(a.length===0){return}var e=$("#board");if(e.length===0){return}var o=function(){var o=$(window).scrollTop()/5;var r=parseInt(e.css("margin-top"),0);var n=96+r;if(o>n){o=n}a.css({transform:"translate3d(0,"+o+"px,0)","-webkit-transform":"translate3d(0,"+o+"px,0)","-ms-transform":"translate3d(0,"+o+"px,0)","-o-transform":"translate3d(0,"+o+"px,0)"});var t=$("#toc");if(t){$("#toc-ctn").css({"padding-top":o+"px"})}};Fluid.utils.listenScroll(o)},registerScrollDownArrowEvent:function(){var o=$(".scroll-down-bar");if(o.length===0){return}o.on("click",function(){Fluid.utils.scrollToElement("#board",-$("#navbar").height())})},registerScrollTopArrowEvent:function(){var t=$("#scroll-top-button");if(t.length===0){return}var a=$("#board");if(a.length===0){return}var e=false;var s=false;var o=function(){var o=a[0].getClientRects()[0].right;var r=document.body.offsetWidth;var n=r-o;e=n>=50;t.css({bottom:e&&s?"20px":"-60px",right:n-64+"px"})};o();$(window).resize(o);var r=a.offset().top;Fluid.utils.listenScroll(function(){var o=document.body.scrollTop+document.documentElement.scrollTop;s=o>=r;t.css({bottom:e&&s?"20px":"-60px"})});t.on("click",function(){$("body,html").animate({scrollTop:0,easing:"swing"})})},registerImageLoadedEvent:function(){if(!("NProgress"in window)){return}var o=document.getElementById("banner");if(o){var r=o.style.backgroundImage;var n=r.match(/\((.*?)\)/)[1].replace(/(['"])/g,"");var t=new Image;t.onload=function(){window.NProgress&&window.NProgress.inc(.2)};t.src=n;if(t.complete){t.onload()}}var a=$("main img:not([lazyload])");var e=a.length;for(const t of a){const s=t.onload;t.onload=function(){s&&s();window.NProgress&&window.NProgress.inc(.5/e)};if(t.complete){t.onload()}}},billboard:function(){if(!("console"in window)){return}console.log(`
------------------------------------------------
|                                              |
|     ________  __            _        __      |
|    |_   __  |[  |          (_)      |  ]     |
|      | |_ \\_| | | __   _   __   .--.| |      |
|      |  _|    | |[  | | | [  |/ /'\`\\' |      |
|     _| |_     | | | \\_/ |, | || \\__/  |      |
|    |_____|   [___]'.__.'_/[___]'.__.;__]     |
|                                              |
|           Powered by Hexo x Fluid            |
|         GitHub: https://git.io/JqpVD         |
|                                              |
------------------------------------------------
    `)}};